import { createSlice } from "@reduxjs/toolkit";

/**
 * GPT Slice
 *
 * Manages state related to GPT/AI features in the app, such as showing info and storing movie results.
 */
const gptSlice = createSlice({
  name: "gpt",
  initialState: {
    // Controls whether GPT info modal/section is visible
    GPTInfo: true,
    // Stores GPT-generated movie results
    movieList: null,
  },
  reducers: {
    /**
     * Show GPT info section
     */
    showGPTInfo: (state) => {
      state.GPTInfo = true;
    },

    /**
     * Hide GPT info section
     */
    hideGPTInfo: (state) => {
      state.GPTInfo = false;
    },

    /**
     * Store GPT movie results
     * @param {Object} action.payload - Movie results generated by GPT
     */
    addGPTMovieResult: (state, action) => {
      state.movieList = action.payload;
    },

    /**
     * Clear GPT movie results
     */
    removeGPTMovieResult: (state) => {
      state.movieList = null;
    },
  },
});

// Export actions for dispatching
export const {
  addGPTMovieResult,
  removeGPTMovieResult,
  showGPTInfo,
  hideGPTInfo,
} = gptSlice.actions;

// Export reducer to include in store
export default gptSlice.reducer;
